; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

#define MyAppName "visitas"
#define MyAppVersion "1.0"
#define MyAppPublisher "My Company, Inc."
#define MyAppURL "http://carlosvin.github.io"
#define MyAppExeName "visitsqt.exe"

[Setup]
; NOTE: The value of AppId uniquely identifies this application.
; Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={{3CDA77DC-DDE1-481B-B17B-CC0A1B911F3F}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
;AppVerName={#MyAppName} {#MyAppVersion}
AppPublisher={#MyAppPublisher}
AppPublisherURL={#MyAppURL}
AppSupportURL={#MyAppURL}
AppUpdatesURL={#MyAppURL}
DefaultDirName={pf}\{#MyAppName}
DefaultGroupName={#MyAppName}
OutputBaseFilename=setup
Compression=lzma
SolidCompression=yes

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"
Name: "spanish"; MessagesFile: "compiler:Languages\Spanish.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked

[Files]
Source: "C:\Documents and Settings\carlos\build-visitsqt-Desktop_Qt_5_3_MinGW_32bit-Release\release\visitsqt.exe"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Documents and Settings\carlos\build-visitsqt-Desktop_Qt_5_3_MinGW_32bit-Release\release\databasemanager.o"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Documents and Settings\carlos\build-visitsqt-Desktop_Qt_5_3_MinGW_32bit-Release\release\icudt52.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Documents and Settings\carlos\build-visitsqt-Desktop_Qt_5_3_MinGW_32bit-Release\release\icuin52.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Documents and Settings\carlos\build-visitsqt-Desktop_Qt_5_3_MinGW_32bit-Release\release\icuuc52.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Documents and Settings\carlos\build-visitsqt-Desktop_Qt_5_3_MinGW_32bit-Release\release\main.o"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Documents and Settings\carlos\build-visitsqt-Desktop_Qt_5_3_MinGW_32bit-Release\release\mainwindow.o"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Documents and Settings\carlos\build-visitsqt-Desktop_Qt_5_3_MinGW_32bit-Release\release\moc_mainwindow.cpp"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Documents and Settings\carlos\build-visitsqt-Desktop_Qt_5_3_MinGW_32bit-Release\release\moc_mainwindow.o"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Documents and Settings\carlos\build-visitsqt-Desktop_Qt_5_3_MinGW_32bit-Release\release\moc_visitdelegate.cpp"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Documents and Settings\carlos\build-visitsqt-Desktop_Qt_5_3_MinGW_32bit-Release\release\moc_visitdelegate.o"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Documents and Settings\carlos\build-visitsqt-Desktop_Qt_5_3_MinGW_32bit-Release\release\moc_visitsmodel.cpp"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Documents and Settings\carlos\build-visitsqt-Desktop_Qt_5_3_MinGW_32bit-Release\release\moc_visitsmodel.o"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Documents and Settings\carlos\build-visitsqt-Desktop_Qt_5_3_MinGW_32bit-Release\release\qt_cs.qm"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Documents and Settings\carlos\build-visitsqt-Desktop_Qt_5_3_MinGW_32bit-Release\release\qt_de.qm"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Documents and Settings\carlos\build-visitsqt-Desktop_Qt_5_3_MinGW_32bit-Release\release\qt_fi.qm"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Documents and Settings\carlos\build-visitsqt-Desktop_Qt_5_3_MinGW_32bit-Release\release\qt_hu.qm"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Documents and Settings\carlos\build-visitsqt-Desktop_Qt_5_3_MinGW_32bit-Release\release\qt_it.qm"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Documents and Settings\carlos\build-visitsqt-Desktop_Qt_5_3_MinGW_32bit-Release\release\qt_ja.qm"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Documents and Settings\carlos\build-visitsqt-Desktop_Qt_5_3_MinGW_32bit-Release\release\qt_ru.qm"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Documents and Settings\carlos\build-visitsqt-Desktop_Qt_5_3_MinGW_32bit-Release\release\qt_sk.qm"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Documents and Settings\carlos\build-visitsqt-Desktop_Qt_5_3_MinGW_32bit-Release\release\qt_uk.qm"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Documents and Settings\carlos\build-visitsqt-Desktop_Qt_5_3_MinGW_32bit-Release\release\Qt5Core.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Documents and Settings\carlos\build-visitsqt-Desktop_Qt_5_3_MinGW_32bit-Release\release\Qt5Gui.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Documents and Settings\carlos\build-visitsqt-Desktop_Qt_5_3_MinGW_32bit-Release\release\Qt5Sql.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Documents and Settings\carlos\build-visitsqt-Desktop_Qt_5_3_MinGW_32bit-Release\release\Qt5Svg.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Documents and Settings\carlos\build-visitsqt-Desktop_Qt_5_3_MinGW_32bit-Release\release\Qt5Widgets.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Documents and Settings\carlos\build-visitsqt-Desktop_Qt_5_3_MinGW_32bit-Release\release\visit.o"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Documents and Settings\carlos\build-visitsqt-Desktop_Qt_5_3_MinGW_32bit-Release\release\visitdelegate.o"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Documents and Settings\carlos\build-visitsqt-Desktop_Qt_5_3_MinGW_32bit-Release\release\visitsmodel.o"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Documents and Settings\carlos\build-visitsqt-Desktop_Qt_5_3_MinGW_32bit-Release\release\visitsqt.exe"; DestDir: "{app}"; Flags: ignoreversion
; NOTE: Don't use "Flags: ignoreversion" on any shared system files

[Icons]
Name: "{group}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"
Name: "{commondesktop}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; Tasks: desktopicon

[Run]
Filename: "{app}\{#MyAppExeName}"; Description: "{cm:LaunchProgram,{#StringChange(MyAppName, '&', '&&')}}"; Flags: nowait postinstall skipifsilent

